# site name
prefixName: 食全
siteName: 食美
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@2.0/CDN/jpg/QQ20200510-2.jpg

url: https://zzl-Alexander.github.io/
description: 食全食美————一个让你欲罢不能的美食APP
#cdn: https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@1.0
pjax: 1
# 1开启
mathjax: 0

notice: 食全食美开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/111.jpg
  - https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/QQ20200510-3.jpg
  - https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/QQ20200510-4.jpg
  - https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/30.jpg
  - https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/QQ20200510-5.jpg
  - https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@2.0/CDN/jpg/QQ20200510-2.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: https://zzl-alexander.github.io/2020/04/26/APP/, title: 食全食美APP, desc: 点击观看, img: https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/30.jpg}
  - {url: https://zzl-alexander.github.io/2020/04/26/APP/, title: 食全食美APP, desc: 点击观看, img: https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@2.0/CDN/jpg/QQ20200510-2.jpg}
  - {url: https://zzl-alexander.github.io/2020/04/26/APP/, title: 食全食美APP, desc: 点击观看, img: https://cdn.jsdelivr.net/gh/zzl-Alexander/CDN@3.0/CDN/jpg/27.jpg}



# your site build time or founded date
siteBuildingTime: 2020/05/10

#social  url, img PC端配置
social:
  github: {url: https://zzl-Alexander.github.io/, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  #email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  #wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/zzl-Alexander, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  #paypal: https://www.paypal.me/hojuncn
  alipay: https://images.cnblogs.com/cnblogs_com/zzl-dreamfly/1636411/o_2001200928176E4F6194996BC13DAB164461F071E36F.jpg
  wechat: https://images.cnblogs.com/cnblogs_com/zzl-dreamfly/1636411/o_200120091900FADAFD93BB431CA300C95D29BB459468.jpg
  #wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

#aplayer: 
 # id: 2660651585
  #server: netease
  #type: playlist
 # fixed: true
 #autoplay: false
  #loop: all
  #order: random
  #preload: auto
  #volume: 0.7
  #mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

